# Generated by Django 3.1.3 on 2020-11-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(verbose_name='Вопрос с множественным выбором ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='surveys.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variants',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_end',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название опроса'),
        ),
    ]
