# Generated by Django 3.1.3 on 2020-11-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveymodel_textquestionmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyModel',
            new_name='Survey',
        ),
        migrations.RenameModel(
            old_name='TextQuestionModel',
            new_name='TextQuestion',
        ),
    ]
