# Generated by Django 3.1.3 on 2020-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20201118_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textquestion',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey',
            field=models.ManyToManyField(related_name='questions', to='surveys.TextQuestion'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
