# Generated by Django 3.1.3 on 2020-11-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20201118_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='answer_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
