# Generated by Django 3.1.3 on 2020-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20201118_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateField(),
        ),
    ]
