# Generated by Django 3.1.3 on 2020-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201118_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variants', models.CharField(blank=True, max_length=1000, null=True)),
                ('multiple_choice', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='answer_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(related_name='questions', to='surveys.Question'),
        ),
    ]
