# Generated by Django 3.1.3 on 2020-11-18 12:06

from django.db import migrations
import multiselectfield.db.fields
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20201118_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, null=True, verbose_name=surveys.models.Question),
        ),
    ]
